#!/usr/bin/env bash
# BeeCount「记账截图」LSPosed 模块 —— 无 Gradle 构建脚本
# 链路：aapt2 编译/链接资源 -> javac -> d8 -> 打包 dex 与 xposed 注册文件 -> zipalign -> apksigner
#
# 改版本号只需要动下面 VERSION_NAME / VERSION_CODE 两行
# （同时记得把 xposed/module.prop 里的 version / versionCode 改成一样的）。
# 产物固定输出到 release/ 目录。
set -e

VERSION_NAME="2.19"
VERSION_CODE="30"

# 脚本自己定位自己 —— 这个仓库可能被放在任何地方，**不要把本机路径写进脚本**。
# （以前这里写死了绝对路径，等于把本机的目录结构一起提交进了仓库。）
#
# 注意 Git Bash：`pwd` 给出来的是 /d/xxx 这种形式，而 java.exe / aapt2.exe / d8 这些
# **原生 Windows 程序只认 D:/xxx**，直接把 /d/xxx 传进去会失败。
# `pwd -W` 就是专门用来拿 Windows 形式路径的，只在 MinGW/MSYS/Cygwin 下存在，
# 所以要用 uname 判断一下再用。
_HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
case "$(uname -s 2>/dev/null)" in
  MINGW*|MSYS*|CYGWIN*)
    _HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -W)" ;;
esac
PROJ="$_HERE"
ROOT="$(dirname "$PROJ")"
TC="$ROOT/toolchain"
JAVA_HOME="$TC/jdk-17.0.20.1+1"
JAVA="$JAVA_HOME/bin/java.exe"
JAVAC="$JAVA_HOME/bin/javac.exe"
KEYTOOL="$JAVA_HOME/bin/keytool.exe"
SDK="$TC/sdk"
BT="$SDK/build-tools/35.0.0"
ANDROID_JAR="$SDK/platforms/android-35/android.jar"
LIBXPOSED="$TC/libxposed/classes.jar"

OUT="$PROJ/build"
APK="$PROJ/release/BeecountShot-v${VERSION_NAME}.apk"
# 打 dex / 打包资源的小脚本需要一个 python：优先 $PYTHON，其次 PATH 里的 python3 / python。
if [ -n "$PYTHON" ]; then
  PY="$PYTHON"
elif command -v python3 >/dev/null 2>&1; then
  PY="python3"
elif command -v python >/dev/null 2>&1; then
  PY="python"
else
  echo "找不到 python。装一个，或者用 PYTHON=/path/to/python 指定。" >&2
  exit 1
fi

echo "=== 0. 清理 ==="
rm -rf "$OUT"
mkdir -p "$OUT/classes" "$OUT/dex" "$OUT/res" "$OUT/gen" "$PROJ/release"

echo "=== 1. aapt2 compile 资源 ==="
"$BT/aapt2.exe" compile --dir "$PROJ/res" -o "$OUT/res.zip"

echo "=== 2. aapt2 link 生成基础 APK + R.java ==="
"$BT/aapt2.exe" link \
  -o "$OUT/base.apk" \
  -I "$ANDROID_JAR" \
  --manifest "$PROJ/AndroidManifest.xml" \
  --java "$OUT/gen" \
  --min-sdk-version 26 \
  --target-sdk-version 35 \
  --version-code "$VERSION_CODE" \
  --version-name "$VERSION_NAME" \
  "$OUT/res.zip"

echo "=== 2b. 生成 BuildInfo.java（版本号的唯一注入点） ==="
# 生成的类放在 gen/ 下，会被下面那条 find 自动收进编译，且不进 src/、不进仓库。
# 这样代码里就再也没机会写死一个过期的版本号（v2.11 的日志里一直打着 v1.3）。
GEN_PKG="$OUT/gen/dev/xtgxiso/beecountshot"
mkdir -p "$GEN_PKG"
cat > "$GEN_PKG/BuildInfo.java" <<EOF
package dev.xtgxiso.beecountshot;

/** Generated by build.sh - do not edit, do not commit. */
final class BuildInfo {
    static final String VERSION_NAME = "$VERSION_NAME";
    static final int VERSION_CODE = $VERSION_CODE;

    private BuildInfo() {
    }
}
EOF
echo "   BuildInfo.VERSION_NAME=$VERSION_NAME VERSION_CODE=$VERSION_CODE"

echo "=== 3. javac 编译 Java 源码（含生成的 R.java 与 BuildInfo.java） ==="
find "$PROJ/src" "$OUT/gen" -name "*.java" > "$OUT/sources.txt"
cat "$OUT/sources.txt"
"$JAVAC" -encoding UTF-8 -source 8 -target 8 -nowarn \
  -bootclasspath "$ANDROID_JAR" \
  -classpath "$LIBXPOSED" \
  -d "$OUT/classes" \
  "@$OUT/sources.txt"

echo "=== 4. 打成 jar 并转 dex ==="
"$JAVA_HOME/bin/jar.exe" cf "$OUT/program.jar" -C "$OUT/classes" .
"$JAVA" -cp "$BT/lib/d8.jar" com.android.tools.r8.D8 \
  --release --lib "$ANDROID_JAR" --min-api 26 \
  --output "$OUT/dex" \
  "$OUT/program.jar"

echo "=== 5. 打包 dex + xposed 注册文件 ==="
"$PY" "$PROJ/pack.py" "$OUT/base.apk" "$OUT/dex/classes.dex" "$PROJ/xposed" "$OUT/unsigned.apk"

echo "=== 6. 检查签名密钥 ==="
# ⚠️ 密钥**故意不放进仓库**，只保留在本地。所以这里不做"缺失就自动生成"——
# 那会悄悄换掉签名，后果是：新包和已装的版本签名不同，必须卸载重装
# （卸载会连带清掉 root 授权和 LSPosed 作用域），而且没有任何提示。
KS="$PROJ/beecount-shot.jks"
if [ ! -f "$KS" ]; then
  echo ""
  echo "  ✗ 找不到签名密钥：$KS"
  echo ""
  echo "    密钥不进仓库（已加进 .gitignore），请从你自己的备份里放回来。"
  echo "    如果你确实要一把全新的密钥（⚠️ 等于换签名，老设备必须卸载重装），"
  echo "    自己手动生成，命令："
  echo ""
  echo "      keytool -genkeypair -noprompt -keystore \"$KS\" \\"
  echo "        -storepass android -keypass android -alias beecountshot \\"
  echo "        -keyalg RSA -keysize 2048 -validity 10000 \\"
  echo "        -dname \"CN=BeecountShot, OU=xtgxiso, O=xtgxiso, L=Beijing, S=Beijing, C=CN\""
  echo ""
  exit 1
fi

echo "=== 7. zipalign 对齐 ==="
"$BT/zipalign.exe" -f -p 4 "$OUT/unsigned.apk" "$OUT/aligned.apk"

echo "=== 8. apksigner 签名 ==="
"$JAVA" -jar "$BT/lib/apksigner.jar" sign \
  --ks "$KS" --ks-pass pass:android --key-pass pass:android \
  --v1-signing-enabled true --v2-signing-enabled true \
  --out "$APK" \
  "$OUT/aligned.apk"

echo "=== 9. 校验签名 ==="
"$JAVA" -jar "$BT/lib/apksigner.jar" verify --print-certs "$APK"

echo "=== 10. 版本号一致性检查 ==="
# 版本号只有 VERSION_NAME / VERSION_CODE 这一个来源，但另外两处文件必须跟着走，
# 漏改的后果是"更新检查停在旧版本"或"模块页显示的版本不对"。这里只警告、不自动改，
# 免得把发布流程里别的东西弄坏。
if ! grep -q "^version=v${VERSION_NAME}$" "$PROJ/xposed/module.prop"; then
  echo "   [警告] xposed/module.prop 的 version 不是 v${VERSION_NAME}"
fi
if ! grep -q "^versionCode=${VERSION_CODE}$" "$PROJ/xposed/module.prop"; then
  echo "   [警告] xposed/module.prop 的 versionCode 不是 ${VERSION_CODE}"
fi
if ! grep -q "v${VERSION_NAME}" "$PROJ/update.json"; then
  echo "   [警告] update.json 还没指向 v${VERSION_NAME}"
fi

echo ""
echo "=== 完成 ==="
ls -la "$APK"
